# Generated by Django 5.0.6 on 2025-01-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Anonymous', max_length=50, verbose_name='Author name')),
                ('title', models.CharField(max_length=100, verbose_name='Article title')),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Publication date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'articles',
            },
        ),
    ]
